# Minimal Python project configuration for linters and type checkers.
# This file centralizes config for ruff, mypy, pre-commit.

[project]
name = "aperisolve"
version = "3.1.3"
description = "Open-source steganalysis web platform for automated image analysis and steganography detection"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "Zeecka"}
]

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",        # pycodestyle errors
    "W",        # pycodestyle warnings
    "F",        # pyflakes
    "I",        # isort
    "UP",       # pyupgrade
    "PL",       # pylint
    "N",        # pep8-naming
    "RUF",      # Ruff-specific rules
    "FURB",     # refurb
    "SIM",      # flake8-simplify
    "A",        # flake8-builtins
    "C4",       # flake8-comprehensions
    "B",        # flake8-bugbear
    "S",        # flake8-bandit
    "DTZ",      # flake8-datetimez
    "PTH",      # flake8-use-pathlib
]
ignore = [
    "E501",     # line too long, handled by ruff
    "C901",     # mccabe complexity
    "PLR2004",  # magic values
    "S324",     # Probable use of insecure hash functions in `hashlib`: `md5`
    "S104",     # Possible binding to all interfaces
]

[tool.ruff.format]
line-ending = "auto"
quote-style = "double"
indent-style = "space"

[tool.mypy]
disallow_any_generics = true
disallow_untyped_defs = true
follow_imports = "skip"
ignore_missing_imports = true

[tool.pre-commit]
skip = true

[tool.doc]
description = """
Linting and type checking configuration for this project.
- Ruff: code formatting + import sorting + code style + code quality
- Mypy: static typing
"""
