name: Linters

on: [push, pull_request]

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          pip install -r aperisolve/requirements-dev.txt
          pip install -r aperisolve/requirements.txt

      - name: Check ruff linter
        run: ruff check --output-format=github .
      
      - name: Check ruff formatter
        run: ruff format --check .
      
      - name: Check mypy
        run: mypy .
